import http from './http'

export const fetchHome = () => http.get('/api/public/home')
export const fetchSite = () => http.get('/api/public/site')
export const fetchArticles = (params) => http.get('/api/public/articles', { params })
export const fetchArticle = (slug) => http.get(`/api/public/articles/${slug}`)
export const searchArticles = (params) => http.get('/api/public/articles/search', { params })
export const fetchCategories = () => http.get('/api/public/categories')
export const fetchCategory = (slug) => http.get(`/api/public/categories/${slug}`)
export const fetchCategoryToc = (idOrSlug) => http.get(`/api/public/categories/${idOrSlug}/toc`)
export const fetchTags = () => http.get('/api/public/tags')
export const fetchProjects = () => http.get('/api/public/projects')
export const fetchComments = (params) => http.get('/api/public/comments', { params })
export const postComment = (data) => http.post('/api/public/comments', data)
export const trackVisit = (path) => http.post('/api/public/visit', { path })
export const fetchAnnouncements = () => http.get('/api/public/announcements')
export const fetchFriendLinks = () => http.get('/api/public/friend-links')
export const fetchCaptcha = () => http.get('/api/public/captcha')

export const registerMember = (data) => http.post('/api/auth/register', data)
export const loginMember = (data) => http.post('/api/auth/login', data)
export const fetchMe = () => http.get('/api/auth/me')
export const updateProfile = (data) => http.put('/api/auth/profile', data)
export const updatePassword = (data) => http.put('/api/auth/password', data)
export const uploadAvatar = (file) => {
  const fd = new FormData()
  fd.append('file', file)
  return http.post('/api/auth/avatar', fd)
}
export const fetchMyComments = (params) => http.get('/api/auth/my-comments', { params })
export const fetchNotifications = (params) => http.get('/api/auth/notifications', { params })
export const markNotificationRead = (id) => http.put(`/api/auth/notifications/${id}/read`)
export const markAllNotificationsRead = () => http.put('/api/auth/notifications/read-all')
export const fetchUnreadCount = () => http.get('/api/auth/notifications/unread-count')
export const saveReadingProgress = (data) => http.post('/api/auth/reading-progress', data)
export const fetchReadingProgress = (params) => http.get('/api/auth/reading-progress', { params })
export const addFavorite = (articleId) => http.post(`/api/auth/favorites/${articleId}`)
export const removeFavorite = (articleId) => http.delete(`/api/auth/favorites/${articleId}`)
export const fetchFavorites = () => http.get('/api/auth/favorites')
export const addSubscription = (categoryId) => http.post(`/api/auth/subscriptions/${categoryId}`)
export const removeSubscription = (categoryId) => http.delete(`/api/auth/subscriptions/${categoryId}`)
export const fetchSubscriptions = () => http.get('/api/auth/subscriptions')
